export const GET_ALL_JOBS = 'GET_ALL_JOBS';
export const GET_ALL_JOBS_FAILED = 'GET_ALL_JOBS_FAILED';
export const UPDATE_JOB = 'UPDATE_JOB';
export const UPDATE_JOB_FAILED = 'UPDATE_JOB_FAILED';
export const POST_JOB_TO_TIMELINE = 'POST_JOB_TO_TIMELINE';
export const POST_JOB_TO_TIMELINE_FAILED = 'POST_JOB_TO_TIMELINE_FAILED';
export const GET_TIMELINE_JOBS = 'GET_TIMELINE_JOBS';
export const GET_TIMELINE_JOBS_FAILED = 'GET_TIMELINE_JOBS_FAILED';